import subprocess
from pathlib import Path
from ..logger import Console, logger


class SecurityService:
    BASE_GITIGNORE = """
# Universal .gitignore generated by Smart Commit
__pycache__/
*.py[cod]
*$py.class
.venv/
venv/
env/
.env*
!.env.example
.vscode/
.idea/
dist/
build/
*.egg-info/
node_modules/
.DS_Store
.smart_commit.log
"""

    @classmethod
    def ensure_gitignore(cls):
        """Ensures .gitignore exists or creates a secure default."""
        path = Path(".gitignore")
        if not path.exists():
            Console.warning(
                ".gitignore not found. Creating a secure default configuration..."
            )
            with open(path, "w", encoding="utf-8") as f:
                f.write(cls.BASE_GITIGNORE.lstrip())
            logger.info("Created default .gitignore")

    @classmethod
    def check_env_leaks(cls):
        """
        Scans for .env* files and uses Git to check if they are ignored.
        Prevents accidental leaks of secrets.
        """
        Console.info("🛡️ Scanning for potential secret leaks (.env files)...")

        env_files = [
            f
            for f in Path(".").rglob(".env*")
            if not any(
                part in ["venv", ".venv", "env", "node_modules", ".git"]
                for part in f.parts
            )
        ]

        leaked_files = []

        for env_file in env_files:
            res = subprocess.run(
                ["git", "check-ignore", "-q", str(env_file)], capture_output=True
            )
            if res.returncode == 1:
                leaked_files.append(str(env_file))

        if leaked_files:
            Console.error(
                "CRITICAL SECURITY RISK: .env files found that are NOT in .gitignore!"
            )
            for lf in leaked_files:
                print(f"  👉 {lf}")

            ans = (
                input("🛑 Add these files to .gitignore automatically? [Y/n]: ")
                .strip()
                .lower()
            )
            if ans != "n":
                with open(".gitignore", "a", encoding="utf-8") as f:
                    f.write("\n# Auto-added by Smart Commit to prevent leaks\n")
                    for lf in leaked_files:
                        f.write(f"{lf}\n")
                Console.success("Files successfully added to .gitignore.")
            else:
                Console.warning(
                    "Action declined. Please be careful: secrets might be pushed!"
                )
