import sys
from pathlib import Path
from .exceptions import SmartCommitError
from .logger import Console, logger

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib


class ConfigService:
    DEFAULT_CONFIG = """
# Auto-generated by Smart Commit
[tool.smart_commit]
repository_url = ""
commands = ["echo 'Running pre-commit pipeline...'"]
protected_branches = ["main", "master", "prod", "release"]
"""

    @classmethod
    def load_or_create(cls) -> dict:
        """Reads configuration. If the section is missing, appends default settings."""
        path = Path("pyproject.toml")

        if not path.exists():
            Console.warning("pyproject.toml not found. Creating a base file...")
            path.touch()

        try:
            with open(path, "rb") as f:
                data = tomllib.load(f)
        except Exception as e:
            raise SmartCommitError(f"Failed to parse pyproject.toml: {e}")

        config = data.get("tool", {}).get("smart_commit")

        if config is None:
            Console.info(
                "Section [tool.smart_commit] not found. Generating default pipeline..."
            )
            logger.info("Appending default tool.smart_commit to pyproject.toml")
            with open(path, "a", encoding="utf-8") as f:
                f.write(cls.DEFAULT_CONFIG)

            with open(path, "rb") as f:
                data = tomllib.load(f)
            config = data.get("tool", {}).get("smart_commit", {})

        return config
